services:
  livekit:
    image: livekit/livekit-server:latest
    network_mode: host
    command:
      - "--dev"
      - "--bind"
      - "0.0.0.0"
    environment:
      LIVEKIT_API_KEY: devkey
      LIVEKIT_API_SECRET: secret

  # Ollama service - commented out since you're running it locally
  # Uncomment if you want to use Docker Ollama instead of local
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0

# volumes:
#   ollama_data:
